language: ruby
cache: bundler

services:
  - mongodb
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 1.9.3
  - jruby-19mode
  - rbx-2

gemfile:
  - gemfiles/active_model_4.1.gemfile
  - gemfiles/active_model_4.2.gemfile
  - gemfiles/active_model_5.0.gemfile
  - gemfiles/active_model_5.1.gemfile
  - gemfiles/active_model_5.2.gemfile
  - gemfiles/active_model_6.0.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
